In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


In [ ]:
# 1. Array Creation

# Creating a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 2D Array:")
print(arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Data type: int64


In [3]:
# Creating a 3D array to demonstrate multidimensional arrays
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)
print("Number of dimensions:", arr_3d.ndim)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Number of dimensions: 3


In [4]:
# 2. Indexing

print("Element at row 2, column 3:", arr[1, 2])
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Last row:", arr[-1])
print("Last element:", arr[-1, -1])

# Indexing a 3D array
print("Element in 3D array:", arr_3d[1, 0, 1])

Element at row 2, column 3: 6
First row: [1 2 3]
First column: [1 4 7]
Last row: [7 8 9]
Last element: 9
Element in 3D array: 6


In [5]:
# 3. Slicing

print("First two rows:")
print(arr[:2])

print("\nFirst two columns:")
print(arr[:, :2])

print("\n2 x 2 sub-array:")
print(arr[0:2, 0:2])

print("\nEvery second column:")
print(arr[:, ::2])

print("\nReversed rows:")
print(arr[::-1])

First two rows:
[[1 2 3]
 [4 5 6]]

First two columns:
[[1 2]
 [4 5]
 [7 8]]

2 x 2 sub-array:
[[1 2]
 [4 5]]

Every second column:
[[1 3]
 [4 6]
 [7 9]]

Reversed rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [6]:
# 4. Reshaping

print("Original shape:", arr.shape)

reshaped_1x9 = arr.reshape(1, 9)
print("\nReshaped to 1 x 9:")
print(reshaped_1x9)

reshaped_9x1 = arr.reshape(9, 1)
print("\nReshaped to 9 x 1:")
print(reshaped_9x1)

reshaped_3x3 = np.arange(1, 10).reshape(3, 3)
print("\nReshaped using arange:")
print(reshaped_3x3)

flattened = arr.reshape(-1)
print("\nFlattened array:")
print(flattened)

Original shape: (3, 3)

Reshaped to 1 x 9:
[[1 2 3 4 5 6 7 8 9]]

Reshaped to 9 x 1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Reshaped using arange:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened array:
[1 2 3 4 5 6 7 8 9]


In [7]:
# 5. Broadcasting

# Scalar broadcasting
print("Original array:")
print(arr)

print("\nAdding 10 to every element using broadcasting:")
print(arr + 10)

print("\nMultiplying every element by 2 using broadcasting:")
print(arr * 2)

# Row-wise broadcasting
row = np.array([10, 20, 30])
print("\nRow array:")
print(row)

print("\nArray + row array:")
print(arr + row)

# Column-wise broadcasting
column = np.array([[10], [20], [30]])
print("\nColumn array:")
print(column)

print("\nArray + column array:")
print(arr + column)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Adding 10 to every element using broadcasting:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplying every element by 2 using broadcasting:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Row array:
[10 20 30]

Array + row array:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Column array:
[[10]
 [20]
 [30]]

Array + column array:
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [8]:
# 6. Mathematical Operations

print("Addition:")
print(arr + 5)

print("\nSubtraction:")
print(arr - 2)

print("\nMultiplication:")
print(arr * 2)

print("\nDivision:")
print(arr / 2)

print("\nPower / Square:")
print(arr ** 2)

print("\nModulo:")
print(arr % 2)

Addition:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Subtraction:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplication:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Division:
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

Power / Square:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Modulo:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [ ]:
# 7. NumPy Mathematical Functions

print("Square root:")
print(np.sqrt(arr))

print("\nExponential:") 
print(np.exp(arr))

print("\nNatural logarithm:")
print(np.log(arr))

print("\nSine:")
print(np.sin(arr))

print("\nCosine:")
print(np.cos(arr))

Square root:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Exponential:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Natural logarithm:
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

Sine:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

Cosine:
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [10]:
# 8. Aggregate Mathematical Operations

print("Sum of all elements:", np.sum(arr))
print("Mean of all elements:", np.mean(arr))
print("Maximum element:", np.max(arr))
print("Minimum element:", np.min(arr))
print("Standard deviation:", np.std(arr))

print("\nSum of each row:")
print(np.sum(arr, axis=1))

print("\nSum of each column:")
print(np.sum(arr, axis=0))

print("\nMean of each row:")
print(np.mean(arr, axis=1))

print("\nMean of each column:")
print(np.mean(arr, axis=0))

Sum of all elements: 45
Mean of all elements: 5.0
Maximum element: 9
Minimum element: 1
Standard deviation: 2.581988897471611

Sum of each row:
[ 6 15 24]

Sum of each column:
[12 15 18]

Mean of each row:
[2. 5. 8.]

Mean of each column:
[4. 5. 6.]
